In [1]:
# Import useful libraries
import numpy as np
import pandas as pd
import requests as req

In [ ]:
pd.set_option("display.max_row", 30)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', 50)

In [ ]:
# Import API from url

url1 = "https://mhw-db.com/weapons"
response = req.get(url1)
response

In [ ]:
data = pd.json_normalize(response.json())
data

,id,type,rarity,elderseal,damageType,name,durability,slots,elements,attack.display,attack.raw,crafting.craftable,crafting.previous,crafting.branches,crafting.craftingMaterials,crafting.upgradeMaterials,assets.icon,assets.image,attributes.affinity,attributes.defense,shelling.type,shelling.level,phial.type,phial.damage,boostType,attributes.boostType,attributes.damageType,specialAmmo,deviation,ammo,coatings,attributes.coatings,assets,attributes.elderseal
0,1,great-sword,1,None,sever,Buster Sword 1,"[{'red': 100, 'orange': 50, 'yellow': 50, 'gre...",[],[],384,80,True,NaN,[2],"[{'quantity': 1, 'item': {'id': 116, 'rarity':...",[],https://assets.mhw-db.com/weapons/great-sword/...,https://assets.mhw-db.com/weapons/great-sword/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,great-sword,1,None,sever,Buster Sword 2,"[{'red': 70, 'orange': 70, 'yellow': 30, 'gree...",[],[],432,90,False,1.0,"[3, 20, 33]",[],"[{'quantity': 2, 'item': {'id': 116, 'rarity':...",https://assets.mhw-db.com/weapons/great-sword/...,https://assets.mhw-db.com/weapons/great-sword/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,great-sword,2,None,sever,Buster Sword 3,"[{'red': 60, 'orange': 70, 'yellow': 30, 'gree...",[],[],480,100,False,2.0,"[4, 11]",[],"[{'quantity': 2, 'item': {'id': 121, 'rarity':...",https://assets.mhw-db.com/weapons/great-sword/...,https://assets.mhw-db.com/weapons/great-sword/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,great-sword,3,None,sever,Buster Blade 1,"[{'red': 70, 'orange': 50, 'yellow': 80, 'gree...",[],[],576,120,False,3.0,[5],[],"[{'quantity': 2, 'item': {'id': 118, 'rarity':...",https://assets.mhw-db.com/weapons/great-sword/...,https://assets.mhw-db.com/weapons/great-sword/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,great-sword,4,None,sever,Buster Blade 2,"[{'red': 60, 'orange': 50, 'yellow': 80, 'gree...",[],[],624,130,False,4.0,[6],[],"[{'quantity': 2, 'item': {'id': 150, 'rarity':...",https://assets.mhw-db.com/weapons/great-sword/...,https://assets.mhw-db.com/weapons/great-sword/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1294,1302,sword-and-shield,8,None,sever,"Kjarr Slicer ""Blast""","[{'red': 100, 'orange': 30, 'yellow': 60, 'gre...",[{'rank': 1}],"[{'type': 'blast', 'damage': 330, 'hidden': Fa...",224,160,False,NaN,[],[],[],NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sever,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1295,1303,sword-and-shield,8,low,sever,"Kjarr Slicer ""Dragon""","[{'red': 160, 'orange': 70, 'yellow': 20, 'gre...",[{'rank': 1}],"[{'type': 'dragon', 'damage': 360, 'hidden': F...",238,170,False,NaN,[],[],[],NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sever,NaN,NaN,NaN,NaN,NaN,NaN,low
1296,1304,sword-and-shield,8,None,sever,"Kjarr Slicer ""King""","[{'red': 80, 'orange': 60, 'yellow': 60, 'gree...",[{'rank': 1}],"[{'type': 'fire', 'damage': 240, 'hidden': Fal...",266,190,False,NaN,[],[],[],NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sever,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1297,1305,sword-and-shield,8,None,sever,"Kjarr Slicer ""Myth""","[{'red': 130, 'orange': 100, 'yellow': 30, 'gr...",[{'rank': 1}],"[{'type': 'thunder', 'damage': 330, 'hidden': ...",238,170,False,NaN,[],[],[],NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sever,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1298,1306,sword-and-shield,8,None,sever,"Kjarr Slicer ""Stream""","[{'red': 100, 'orange': 30, 'yellow': 60, 'gre...",[{'rank': 1}],"[{'type': 'ice', 'damage': 300, 'hidden': False}]",238,170,False,NaN,[],[],[],NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sever,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
cols = data.columns.values
cols

array(['id', 'type', 'rarity', 'elderseal', 'damageType', 'name',
       'durability', 'slots', 'elements', 'attack.display', 'attack.raw',
       'crafting.craftable', 'crafting.previous', 'crafting.branches',
       'crafting.craftingMaterials', 'crafting.upgradeMaterials',
       'assets.icon', 'assets.image', 'attributes.affinity',
       'attributes.defense', 'shelling.type', 'shelling.level',
       'phial.type', 'phial.damage', 'boostType', 'attributes.boostType',
       'attributes.damageType', 'specialAmmo', 'deviation', 'ammo',
       'coatings', 'attributes.coatings', 'assets',
       'attributes.elderseal'], dtype=object)

In [ ]:
# Subset with information to be used
wdata = data[['id', 'name', 'type', 'damageType', 'attack.display', 'attack.raw', 'elements', 'attributes.affinity', 'durability', 'slots']]
wdata

,id,name,type,damageType,attack.display,attack.raw,elements,attributes.affinity,durability,slots
0,1,Buster Sword 1,great-sword,sever,384,80,[],NaN,"[{'red': 100, 'orange': 50, 'yellow': 50, 'gre...",[]
1,2,Buster Sword 2,great-sword,sever,432,90,[],NaN,"[{'red': 70, 'orange': 70, 'yellow': 30, 'gree...",[]
2,3,Buster Sword 3,great-sword,sever,480,100,[],NaN,"[{'red': 60, 'orange': 70, 'yellow': 30, 'gree...",[]
3,4,Buster Blade 1,great-sword,sever,576,120,[],NaN,"[{'red': 70, 'orange': 50, 'yellow': 80, 'gree...",[]
4,5,Buster Blade 2,great-sword,sever,624,130,[],NaN,"[{'red': 60, 'orange': 50, 'yellow': 80, 'gree...",[]
...,...,...,...,...,...,...,...,...,...,...
1294,1302,"Kjarr Slicer ""Blast""",sword-and-shield,sever,224,160,"[{'type': 'blast', 'damage': 330, 'hidden': Fa...",10,"[{'red': 100, 'orange': 30, 'yellow': 60, 'gre...",[{'rank': 1}]
1295,1303,"Kjarr Slicer ""Dragon""",sword-and-shield,sever,238,170,"[{'type': 'dragon', 'damage': 360, 'hidden': F...",10,"[{'red': 160, 'orange': 70, 'yellow': 20, 'gre...",[{'rank': 1}]
1296,1304,"Kjarr Slicer ""King""",sword-and-shield,sever,266,190,"[{'type': 'fire', 'damage': 240, 'hidden': Fal...",15,"[{'red': 80, 'orange': 60, 'yellow': 60, 'gree...",[{'rank': 1}]
1297,1305,"Kjarr Slicer ""Myth""",sword-and-shield,sever,238,170,"[{'type': 'thunder', 'damage': 330, 'hidden': ...",10,"[{'red': 130, 'orange': 100, 'yellow': 30, 'gr...",[{'rank': 1}]
1298,1306,"Kjarr Slicer ""Stream""",sword-and-shield,sever,238,170,"[{'type': 'ice', 'damage': 300, 'hidden': False}]",10,"[{'red': 100, 'orange': 30, 'yellow': 60, 'gre...",[{'rank': 1}]

In [ ]:
wdata["type"].unique()

array(['great-sword', 'long-sword', 'sword-and-shield', 'dual-blades',
       'hammer', 'hunting-horn', 'lance', 'gunlance', 'switch-axe',
       'charge-blade', 'insect-glaive', 'light-bowgun', 'heavy-bowgun',
       'bow'], dtype=object)

In [ ]:
wdata.dtypes

id                      int64
name                   object
type                   object
damageType             object
attack.display          int64
attack.raw              int64
elements               object
attributes.affinity    object
durability             object
slots                  object
dtype: object

In [ ]:
# 1 of the weapons has a double type and data is contained in a list containing 2 dictionaries. 
# Upon exploding them, it creates 2 entries, 1 for each elements, thus adding an additional row
wdata[wdata["id"]==343]["elements"].values

array([list([{'type': 'ice', 'damage': 240, 'hidden': False}, {'type': 'blast', 'damage': 240, 'hidden': False}])],
      dtype=object)

In [ ]:
# Solution: since this is only for 1 row and the "damage" value is the same for both elements,
# I replaced the value with the following: 
wdata.iloc[342,6] = [{'type': 'ice/blast', 'damage': 240, 'hidden': False}]

In [ ]:
# Unpacking values from "elements"
elements = pd.DataFrame(wdata.loc[:,["id","elements"]])
elements

        id                                           elements
0        1                                                 []
1        2                                                 []
2        3                                                 []
3        4                                                 []
4        5                                                 []
...    ...                                                ...
1294  1302  [{'type': 'blast', 'damage': 330, 'hidden': Fa...
1295  1303  [{'type': 'dragon', 'damage': 360, 'hidden': F...
1296  1304  [{'type': 'fire', 'damage': 240, 'hidden': Fal...
1297  1305  [{'type': 'thunder', 'damage': 330, 'hidden': ...
1298  1306  [{'type': 'ice', 'damage': 300, 'hidden': False}]

[1299 rows x 2 columns]

In [ ]:
# Replace empty data as we cannot drop the empty lists -> we must set a default value for the empty lists 
# Why this method? Seems Pandas does not recognize empty list as NaN, nor as "[]". Hence, we need a reference column.
# 1. Create list with bool values
empty = []
for i in range(len(elements)):
    if len(elements["elements"][i]) == 0:
        empty.append(True) # elements is empty
    else:
        empty.append(False) # elements is filled in

In [ ]:
# 2. Add column "empty" to our DF
elements["empty"] = empty
elements

        id                                           elements  empty
0        1                                                 []   True
1        2                                                 []   True
2        3                                                 []   True
3        4                                                 []   True
4        5                                                 []   True
...    ...                                                ...    ...
1294  1302  [{'type': 'blast', 'damage': 330, 'hidden': Fa...  False
1295  1303  [{'type': 'dragon', 'damage': 360, 'hidden': F...  False
1296  1304  [{'type': 'fire', 'damage': 240, 'hidden': Fal...  False
1297  1305  [{'type': 'thunder', 'damage': 330, 'hidden': ...  False
1298  1306  [{'type': 'ice', 'damage': 300, 'hidden': False}]  False

[1299 rows x 3 columns]

In [ ]:
# 3. Based on the values in "empty", replace the [] with a default value for rows that have a True value in "empty"
for i in range(len(elements)):
    if elements.iloc[i,2] == True:
        elements.iloc[i,1] = [{"type":"None", "damage":0, "hidden":False}]
    else:
        continue

In [ ]:
elements = elements.drop(columns="empty") # drop "empty" column (no longer needed)
elements = elements.explode("elements") # converts lists into dictionaries

In [ ]:
# for each row, return all values from the dictionnaries and append them to our DF as new columns 
def extract_values(dictionary):
    type = dictionary["type"]
    damage = dictionary["damage"]
    hidden = dictionary["hidden"]
    return type, damage, hidden

elements[["element_type","element_damage", "element_hidden"]] = elements["elements"].apply(lambda x:pd.Series(extract_values(x)))

In [ ]:
# As expected, 1 of the weapons has a new element-type, which is the combination of its original elements ('ice/blast')
elements["element_type"].unique()

array(['None', 'poison', 'dragon', 'thunder', 'ice', 'water', 'paralysis',
       'fire', 'sleep', 'blast', 'ice/blast'], dtype=object)

In [ ]:
elements

,id,elements,element_type,element_damage,element_hidden
0,1,"{'type': 'None', 'damage': 0, 'hidden': False}",None,0,False
1,2,"{'type': 'None', 'damage': 0, 'hidden': False}",None,0,False
2,3,"{'type': 'None', 'damage': 0, 'hidden': False}",None,0,False
3,4,"{'type': 'None', 'damage': 0, 'hidden': False}",None,0,False
4,5,"{'type': 'None', 'damage': 0, 'hidden': False}",None,0,False
...,...,...,...,...,...
1294,1302,"{'type': 'blast', 'damage': 330, 'hidden': False}",blast,330,False
1295,1303,"{'type': 'dragon', 'damage': 360, 'hidden': Fa...",dragon,360,False
1296,1304,"{'type': 'fire', 'damage': 240, 'hidden': False}",fire,240,False
1297,1305,"{'type': 'thunder', 'damage': 330, 'hidden': F...",thunder,330,False
1298,1306,"{'type': 'ice', 'damage': 300, 'hidden': False}",ice,300,False

In [ ]:
# Unpack durability
# Problem 1: 6 levels of durability (basic level + 1 level per level of Sharpness skill)
# Problem 2: 3 weapon types do not have durability 
# 1) Create a DF, excluding weapons without durability
durability = wdata[~wdata["type"].isin(['light-bowgun', 'heavy-bowgun', 'bow'])]
durability = durability.loc[:,["id","durability"]]

In [ ]:
# Convert all lists into dictionaries
durability_all = durability.explode("durability")
durability_all

        id                                         durability
0        1  {'red': 100, 'orange': 50, 'yellow': 50, 'gree...
0        1  {'red': 100, 'orange': 50, 'yellow': 60, 'gree...
0        1  {'red': 100, 'orange': 50, 'yellow': 70, 'gree...
0        1  {'red': 100, 'orange': 50, 'yellow': 80, 'gree...
0        1  {'red': 100, 'orange': 50, 'yellow': 80, 'gree...
...    ...                                                ...
1298  1306  {'red': 100, 'orange': 30, 'yellow': 60, 'gree...
1298  1306  {'red': 100, 'orange': 30, 'yellow': 60, 'gree...
1298  1306  {'red': 100, 'orange': 30, 'yellow': 60, 'gree...
1298  1306  {'red': 100, 'orange': 30, 'yellow': 60, 'gree...
1298  1306  {'red': 100, 'orange': 30, 'yellow': 60, 'gree...

[6060 rows x 2 columns]

In [ ]:
# 2) Get all values from every dictionary
def extract_values(dictionary):
    red = dictionary["red"]
    orange = dictionary["orange"]
    yellow = dictionary["yellow"]
    green = dictionary["green"]
    blue = dictionary["blue"]
    white =  dictionary["white"]
    purple = dictionary["purple"]
    return red, orange, yellow, green, blue, white, purple

durability_all[["red","orange", "yellow", "green", "blue", "white", "purple"]] = durability_all["durability"].apply(lambda x:pd.Series(extract_values(x)))
durability_all

,id,durability,red,orange,yellow,green,blue,white,purple
0,1,"{'red': 100, 'orange': 50, 'yellow': 50, 'gree...",100,50,50,0,0,0,0
0,1,"{'red': 100, 'orange': 50, 'yellow': 60, 'gree...",100,50,60,0,0,0,0
0,1,"{'red': 100, 'orange': 50, 'yellow': 70, 'gree...",100,50,70,0,0,0,0
0,1,"{'red': 100, 'orange': 50, 'yellow': 80, 'gree...",100,50,80,0,0,0,0
0,1,"{'red': 100, 'orange': 50, 'yellow': 80, 'gree...",100,50,80,10,0,0,0
...,...,...,...,...,...,...,...,...,...
1298,1306,"{'red': 100, 'orange': 30, 'yellow': 60, 'gree...",100,30,60,80,40,50,0
1298,1306,"{'red': 100, 'orange': 30, 'yellow': 60, 'gree...",100,30,60,80,40,60,0
1298,1306,"{'red': 100, 'orange': 30, 'yellow': 60, 'gree...",100,30,60,80,40,70,0
1298,1306,"{'red': 100, 'orange': 30, 'yellow': 60, 'gree...",100,30,60,80,40,80,0
1298,1306,"{'red': 100, 'orange': 30, 'yellow': 60, 'gree...",100,30,60,80,40,90,0

In [ ]:
# We wish to get the base and max durability for all weapons (add total column)
durability_all["total_durability"] = (durability_all["red"]
                                  + durability_all["orange"]
                                  + durability_all["yellow"]
                                  + durability_all["green"]
                                  + durability_all["blue"]
                                  + durability_all["white"]
                                  + durability_all["purple"])
durability_all[durability_all["id"]==1]

,id,durability,red,orange,yellow,green,blue,white,purple,total_durability
0,1,"{'red': 100, 'orange': 50, 'yellow': 50, 'gree...",100,50,50,0,0,0,0,200
0,1,"{'red': 100, 'orange': 50, 'yellow': 60, 'gree...",100,50,60,0,0,0,0,210
0,1,"{'red': 100, 'orange': 50, 'yellow': 70, 'gree...",100,50,70,0,0,0,0,220
0,1,"{'red': 100, 'orange': 50, 'yellow': 80, 'gree...",100,50,80,0,0,0,0,230
0,1,"{'red': 100, 'orange': 50, 'yellow': 80, 'gree...",100,50,80,10,0,0,0,240
0,1,"{'red': 100, 'orange': 50, 'yellow': 80, 'gree...",100,50,80,20,0,0,0,250

In [ ]:
# Select min and max values for durability
min_durability = durability_all.iloc[::6]
max_durability = durability_all.iloc[5::6]

In [ ]:
durability["base_durability"] = min_durability["total_durability"]
durability["max_durability"] = max_durability["total_durability"]

In [ ]:
# To use in final weapons DF
durability

,id,durability,base_durability,max_durability
0,1,"[{'red': 100, 'orange': 50, 'yellow': 50, 'gre...",200,250
1,2,"[{'red': 70, 'orange': 70, 'yellow': 30, 'gree...",200,250
2,3,"[{'red': 60, 'orange': 70, 'yellow': 30, 'gree...",200,250
3,4,"[{'red': 70, 'orange': 50, 'yellow': 80, 'gree...",250,300
4,5,"[{'red': 60, 'orange': 50, 'yellow': 80, 'gree...",250,300
...,...,...,...,...
1294,1302,"[{'red': 100, 'orange': 30, 'yellow': 60, 'gre...",350,400
1295,1303,"[{'red': 160, 'orange': 70, 'yellow': 20, 'gre...",350,400
1296,1304,"[{'red': 80, 'orange': 60, 'yellow': 60, 'gree...",350,400
1297,1305,"[{'red': 130, 'orange': 100, 'yellow': 30, 'gr...",350,400
1298,1306,"[{'red': 100, 'orange': 30, 'yellow': 60, 'gre...",350,400

In [ ]:
# Save all durability values in another csv (for future use)
full_durability = durability_all.drop(columns=["durability", "total_durability"])

In [ ]:
# Insert a reference column to list all values for each weapon
full_durability.insert(1, "level_durability", None)

In [ ]:
# Add values through iloc slicing
full_durability.iloc[0::6,1]= "base"
full_durability.iloc[1::6,1]= "sharpness +1"
full_durability.iloc[2::6,1]= "sharpness +2"
full_durability.iloc[3::6,1]= "sharpness +3"
full_durability.iloc[4::6,1]= "sharpness +4"
full_durability.iloc[5::6,1]= "sharpness +5"

In [ ]:
full_durability

        id level_durability  red  orange  yellow  green  blue  white  purple
0        1             base  100      50      50      0     0      0       0
0        1     sharpness +1  100      50      60      0     0      0       0
0        1     sharpness +2  100      50      70      0     0      0       0
0        1     sharpness +3  100      50      80      0     0      0       0
0        1     sharpness +4  100      50      80     10     0      0       0
...    ...              ...  ...     ...     ...    ...   ...    ...     ...
1298  1306     sharpness +1  100      30      60     80    40     50       0
1298  1306     sharpness +2  100      30      60     80    40     60       0
1298  1306     sharpness +3  100      30      60     80    40     70       0
1298  1306     sharpness +4  100      30      60     80    40     80       0
1298  1306     sharpness +5  100      30      60     80    40     90       0

[6060 rows x 9 columns]

In [ ]:
full_durability.to_csv(path_or_buf="./MHW_weapons_full_sharpness_values.csv")

In [ ]:
# Unpack slots : get total amount of slots for each weapon
slots = pd.DataFrame(wdata.loc[:,["id","slots"]])
len(slots.iloc[700,1])

1

In [ ]:
total_slots = []
for i in range(len(slots)):
    total_slots.append(len(slots.iloc[i,1]))

In [ ]:
# To use
slots["total_slots"] = total_slots
slots

        id          slots  total_slots
0        1             []            0
1        2             []            0
2        3             []            0
3        4             []            0
4        5             []            0
...    ...            ...          ...
1294  1302  [{'rank': 1}]            1
1295  1303  [{'rank': 1}]            1
1296  1304  [{'rank': 1}]            1
1297  1305  [{'rank': 1}]            1
1298  1306  [{'rank': 1}]            1

[1299 rows x 3 columns]

In [ ]:
# Finalize DF and export to workable CSV
wdata.loc[:,"total_slots"] = slots.loc[:,"total_slots"]
wdata.loc[:,"base_durability"] = durability.loc[:,"base_durability"]
wdata.loc[:,"max_durability"] = durability.loc[:,"max_durability"]
wdata.loc[:,["element_type", "element_damage", "element_hidden"]] = elements.loc[:,["element_type",	"element_damage", "element_hidden"]]

In [ ]:
# Get rid of cleaned columns
weapon_final = wdata.drop(columns=["elements","durability", "slots"])

In [ ]:
# Clean nulls, replace "True" and "False" with "Yes" and "No" (more user friendly in this case)
weapon_final.loc[:,"element_hidden"] = weapon_final["element_hidden"].replace(to_replace=[False, True], value=["No", "Yes"])
weapon_final.loc[:,"attributes.affinity"] = weapon_final["attributes.affinity"].fillna(0)

In [ ]:
# Explicit certain column names
weapon_to_export = weapon_final.rename(columns={
    "damageType" : "damage_type",
    "attack.display" : "attack",
    "attack.raw" : "raw",
    "attributes.affinity" : "affinity",
    "element_type" : "elements"
})

In [ ]:
weapon_to_export

,id,name,type,damage_type,attack,raw,affinity,total_slots,base_durability,max_durability,elements,element_damage,element_hidden
0,1,Buster Sword 1,great-sword,sever,384,80,0,0,200.0,250.0,None,0,No
1,2,Buster Sword 2,great-sword,sever,432,90,0,0,200.0,250.0,None,0,No
2,3,Buster Sword 3,great-sword,sever,480,100,0,0,200.0,250.0,None,0,No
3,4,Buster Blade 1,great-sword,sever,576,120,0,0,250.0,300.0,None,0,No
4,5,Buster Blade 2,great-sword,sever,624,130,0,0,250.0,300.0,None,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1294,1302,"Kjarr Slicer ""Blast""",sword-and-shield,sever,224,160,10,1,350.0,400.0,blast,330,No
1295,1303,"Kjarr Slicer ""Dragon""",sword-and-shield,sever,238,170,10,1,350.0,400.0,dragon,360,No
1296,1304,"Kjarr Slicer ""King""",sword-and-shield,sever,266,190,15,1,350.0,400.0,fire,240,No
1297,1305,"Kjarr Slicer ""Myth""",sword-and-shield,sever,238,170,10,1,350.0,400.0,thunder,330,No
1298,1306,"Kjarr Slicer ""Stream""",sword-and-shield,sever,238,170,10,1,350.0,400.0,ice,300,No

In [ ]:
# Export to csv
weapon_to_export.to_csv(path_or_buf="./MH_API_weapons.csv")